# Generated by Django 5.2 on 2025-05-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_tag_alter_post_data_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-data']},
        ),
    ]
